name: "Push OAS to github"
description: "Push OAS to github"
inputs:
  PAT:
    description: 'A Github key'
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.PAT }}
          ref: ${{ github.head_ref }}

      - name: Push OAS to github
        shell: bash
        run: |
          echo "${{ github.head_ref }}" > /tmp/branch.txt
          if ! cmp -s "/tmp/branch.txt" ".github/tmp/branch.txt" ; then
          cp /tmp/branch.txt .github/tmp/branch.txt
          exit 1
          fi

      - name: Update Git
        if: failure()
        shell: bash
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git fetch
          git pull
          git add .github/tmp/branch.txt
          git commit -m "Update BranchReference from GitHub Actions"
          git push origin "${{ github.head_ref }}"