name: Build And Upload to OTA

inputs:
  Build-ENVL:
    description: matrix.Build-ENV
    required: true
  Build-USER:
    description: secrets.BUIUSER
    required: true
  Build-PASSWORD:
    description: secrets.BUIPASSWORD
    required: true
  Build-OTA-APIKEY:
    description: secrets.OTASHARE_APIKEY
    required: true
  Build-OTA-APIKEY-BUILD:
    description: secrets.OTASHARE_APIKEY_BUILD
    required: true
  Build-KEY-STORE:
    description: secrets.BUILD_KEYSTORE
    required: true
  Build-KEY-ALIAS:
    description: secrets.BUILD_KEY_ALIAS
    required: true
  Build-KEY-PASSWORD:
    description: secrets.BUILD_KEY_PASSWORD
    required: true
  Build-STORE-PASSWORD:
    description: secrets.BUILD_STORE_PASSWORD
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        cache: gradle
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
    - name: Decode Keystore
      env:
        BUILD_KEYSTORE: ${{ inputs.Build-KEY-STORE }}
      shell: bash
      run: |
        echo $BUILD_KEYSTORE | base64 --decode > -o "./esmorga.keystore.jks"

    - name: Sign app
      shell: bash
      run: ./gradlew app:bundleRelease
      env:
#        STORE_FILE_PATH: esmorga.keystore.jks
        BUILD_KEY_ALIAS: ${{ inputs.Build-KEY-ALIAS }}
        BUILD_KEY_PASSWORD: ${{ inputs.Build-KEY-PASSWORD }}
        BUILD_STORE_PASSWORD: ${{ inputs.Build-STORE-PASSWORD }}
    - name: Build with Gradle
      shell: bash
      env:
        BUILD_KEY_ALIAS: ${{ inputs.Build-KEY-ALIAS }}
        BUILD_KEY_PASSWORD: ${{ inputs.Build-KEY-PASSWORD }}
        BUILD_STORE_PASSWORD: ${{ inputs.Build-STORE-PASSWORD }}
      run: ./gradlew :app:assemble${{ inputs.Build-ENVL }}Release
    - shell: bash
      run: |
        
        rootDir="./"
        GRADLE_FILE=$rootDir"app/build.gradle.kts"
        file=$rootDir"app/build/outputs/apk/${{ inputs.Build-ENVL }}/release/app-${{ inputs.Build-ENVL }}-release.apk"
        name=Esmorga
        versionName=$(grep "versionName" $GRADLE_FILE | awk '{print $3}')
        versionCode=$(grep "versionCode" $GRADLE_FILE | awk '{print $3}')
        
        buildHash=$(md5sum $file | awk '{print $4}')
        
        project_id=2793
        api_key=${{ inputs.Build-OTA-APIKEY }}
        api_key_build=${{ inputs.Build-OTA-APIKEY-BUILD }}
        visibleClient=true
        BuildENVL="$(echo ${{ inputs.Build-ENVL }} | tr a-z A-Z )"
        buildType="$BuildENVL"
        name="Esmorga [$BuildENVL]"
        
        curl -vvv -F "buiFile=@${file}" \
            -F "buiName=${name}" \
            -F "buiVersion=${versionName}" \
            -F "buiBuildNum=${versionCode}" \
            -F "buiBuildType=${buildType}" \
            -F "buiTemplate=0" \
            -F "buiHash=${buildHash}" \
            -F "buiVisibleClient=${visibleClient}" \
            -F "buiChangeLog=none" \
            -F "buiUser=${{ inputs.Build-USER }}" -F "buiPassword=${{ inputs.Build-PASSWORD }}" \
            "https://otashare-api.mobgen.com/v1/builds/registernewbuild/${project_id}/${api_key}/${api_key_build}"