name: Build And Upload to OTA

inputs:
  Build-ENVL:
    description: matrix.Build-ENV
    required: true
  Build-USER:
    description: secrets.BUIUSER
    required: true
  Build-PASSWORD:
    description: secrets.BUIPASSWORD
    required: true
  Build-OTA-APIKEY:
    description: secrets.OTASHARE_APIKEY
    required: true
  Build-OTA-APIKEY-BUILD:
    description: secrets.OTASHARE_APIKEY_BUILD
    required: true
  Build-KEY-STORE:
    description: secrets.BUILD_KEYSTORE
    required: true
  Build-KEY-ALIAS:
    description: secrets.BUILD_KEY_ALIAS
    required: true
  Build-KEY-PASSWORD:
    description: secrets.BUILD_KEY_PASSWORD
    required: true
  Build-STORE-PASSWORD:
    description: secrets.BUILD_STORE_PASSWORD
    required: true
  E2E-Github-Token:
    description: secrets.E2E_Github_Token
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        cache: gradle
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
    - name: Decode Keystore
      env:
        BUILD_KEYSTORE: ${{ inputs.Build-KEY-STORE }}
      shell: bash
      run: |
        echo $BUILD_KEYSTORE | base64 --decode > esmorgabuild.keystore.jks
    - name: Build with Gradle
      shell: bash
      env:
        BUILD_KEY_ALIAS: ${{ inputs.Build-KEY-ALIAS }}
        BUILD_KEY_PASSWORD: ${{ inputs.Build-KEY-PASSWORD }}
        BUILD_STORE_PASSWORD: ${{ inputs.Build-STORE-PASSWORD }}
      run: ./gradlew :app:assemble${{ inputs.Build-ENVL }}Release
    - shell: bash
      id: otashare_file_url 
      run: |
        
        rootDir="./"
        GRADLE_FILE=$rootDir"app/build.gradle.kts"
        file=$rootDir"app/build/outputs/apk/${{ inputs.Build-ENVL }}/release/app-${{ inputs.Build-ENVL }}-release.apk"
        name=Esmorga
        versionName=$(grep "versionName" $GRADLE_FILE | awk '{print $3}')
        versionCode=$(grep "versionCode" $GRADLE_FILE | awk '{print $3}')
        
        buildHash=$(md5sum $file | awk '{print $4}')
        
        project_id=2793
        api_key=${{ inputs.Build-OTA-APIKEY }}
        api_key_build=${{ inputs.Build-OTA-APIKEY-BUILD }}
        visibleClient=true
        BuildENVL="$(echo ${{ inputs.Build-ENVL }} | tr a-z A-Z )"
        buildType="$BuildENVL"
        name="Esmorga [$BuildENVL]"
        function main
        {
          curl -vs -F "buiFile=@${file}" \
              -F "buiName=${name}" \
              -F "buiVersion=${versionName}" \
              -F "buiBuildNum=${versionCode}" \
              -F "buiBuildType=${buildType}" \
              -F "buiTemplate=0" \
              -F "buiHash=${buildHash}" \
              -F "buiVisibleClient=${visibleClient}" \
              -F "buiChangeLog=none" \
              -F "buiUser=${{ inputs.Build-USER }}" -F "buiPassword=${{ inputs.Build-PASSWORD }}" \
              "https://otashare-api.mobgen.com/v1/builds/registernewbuild/${project_id}/${api_key}/${api_key_build}" \
              2>&1
        }
        OUT=$(main)
        echo "url=$(echo "$OUT" | grep https)" >> $GITHUB_OUTPUT

    - name: Trigger Workflow
      description: Run E2E test Just for QA after upload apk to otashare
      env:
        github-token: ${{ inputs.E2E-Github-Token }}
      if: "${{ inputs.Build-ENVL == 'qa' }}"
      shell: bash
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.E2E-Github-Token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/Esmorga-E2E/E2E-APP-Tests/actions/workflows/RunTest.yml/dispatches \
        -d '{"ref":"main","inputs":{"build_url":${{steps.otashare_file_url.outputs.url}},"OS":"android"}}'


                    