name: Run Tests

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
    - name: Test with Gradle
      shell: bash
      run: ./gradlew koverXmlReport
    - name: Add coverage report to PR
      id: kover
      uses: mi-kas/kover-report@v1
      with:
        path: |
          ${{ github.workspace }}/build/reports/kover/report.xml
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 75
        min-coverage-changed-files: 75
        coverage-counter-type: LINE