name: Run Tests

inputs:
  Build-GOOGLE-SERVICES:
    description: secrets.GOOGLE_SERVICES_JSON
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        cache: gradle
    - name: Create google-services.json
      shell: bash
      run: |
        echo "${{ inputs.Build-GOOGLE-SERVICES }}" > /home/runner/work/EsmorgaAndroid/EsmorgaAndroid/app/google-services.json
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
    - name: Test with Gradle
      shell: bash
      run: ./gradlew koverXmlReport