name: Self-Hosted Runner Example

on:
  push:


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a simple test
      run: |
        npm ci
        npx wdio run ./wdio.conf.js

